[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "salt-portal-backup"
version = "0.2.1"
description = 'Backup projects, stations, calibrations and measurements from Salt Portal to a SQLite database.'
readme = "README.md"
requires-python = ">=3.11"
license = "BSD-3-Clause"
keywords = []
authors = [
  { name = "Reinert Huseby Karlsen", email = "rhkarls@proton.me" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]

dependencies = [
    "sqlalchemy>=2.0.37",
    "beautifulsoup4>=4.14.0",
    "pandas>=3.0.0",
    "numpy>=2.4.0",
    "requests>=2.32.3",
    "click>=8.3.0",
    "tqdm>=4.67.1"
]

[project.urls]
Documentation = "https://github.com/rhkarls/salt-portal-backup#readme"
Issues = "https://github.com/rhkarls/salt-portal-backup/issues"
Source = "https://github.com/rhkarls/salt-portal-backup"

[project.scripts]
salt_portal_backup = "salt_portal_backup.backup:main"

[tool.ruff]
line-length = 88
lint.select = [
  "B", # flake8-bugbear rules
  "E", # pycodestyle error rules
  "F", # pyflakes rules
  "I", # isort rules
  "W", # pycodestyle warning rules
]
lint.ignore = [
  "E501", # line-too-long
]

[tool.uv]
default-groups = [ "dev"]
exclude-newer = "15 days"

[tool.numpydoc_validation]
checks = [
  "all",  # report on all checks
  "ES01", # but don't require an extended summary
  "EX01", # or examples
  "SA01", # or a see also section
  "SS06", # and don't require the summary to fit on one line
]
exclude = [ # don't report on checks for these
  '\\.__init__$',
  '\\.__repr__$',
  '\\.__str__$',
]

[dependency-groups]
dev = [
    "build>=1.4.3",
    "pyinstaller>=6.19.0",
    "ruff>=0.15.11",
    "twine>=6.2.0",
    "pyrefly>=0.60.0"
]
